name: Publish to npm

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT }}
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - run: |
          git config --global user.email "fcalldas@gmail.com"
          git config --global user.name "Felipe Caldas"
      - run: |
          if ! git diff --quiet; then
            npm version patch -m "Upgrade to %s"
            git push --follow-tags
          else
            echo "No changes to commit"
          fi
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
