name: Node.js Package

on:
  push:
    branches:
      - main

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT }}
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - run: |
          git config --global user.email "fcalldas@gmail.com"
          git config --global user.name "Felipe Caldas"
      - run: |
          npm version patch -m "Upgrade to %s"
          git remote set-url origin https://x-access-token:${{ secrets.PAT }}@github.com/felipecal/easy-message-broker.git
          git push --follow-tags
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
